import pandas as pd

from nbatools.commands.natural_query import parse_query
from nbatools.commands.player_compare import _build_player_head_to_head_frames
from nbatools.commands.team_compare import _build_team_head_to_head_frames


def test_parse_compare_queries_set_head_to_head_flag():
    parsed = parse_query("Embiid head-to-head vs Jokic")
    assert parsed["route"] == "player_compare"
    assert parsed["route_kwargs"]["head_to_head"] is True

    parsed = parse_query("Lakers head-to-head vs Celtics")
    assert parsed["route"] == "team_compare"
    assert parsed["route_kwargs"]["head_to_head"] is True

    parsed = parse_query("Jokic vs Embiid")
    assert parsed["route"] == "player_compare"
    assert parsed["route_kwargs"]["head_to_head"] is False


def test_team_head_to_head_frames_only_keep_shared_matchups_and_primary_home_filter():
    df = pd.DataFrame(
        [
            {
                "game_id": 1,
                "game_date": "2099-10-01",
                "season": "2099-00",
                "season_type": "Regular Season",
                "team_id": 1,
                "team_abbr": "ALP",
                "team_name": "Alpha",
                "opponent_team_id": 2,
                "opponent_team_abbr": "BET",
                "opponent_team_name": "Beta",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "pts": 100,
                "reb": 40,
                "ast": 25,
                "stl": 8,
                "blk": 5,
                "fg3m": 12,
                "tov": 11,
                "plus_minus": 10,
            },
            {
                "game_id": 1,
                "game_date": "2099-10-01",
                "season": "2099-00",
                "season_type": "Regular Season",
                "team_id": 2,
                "team_abbr": "BET",
                "team_name": "Beta",
                "opponent_team_id": 1,
                "opponent_team_abbr": "ALP",
                "opponent_team_name": "Alpha",
                "is_home": 0,
                "is_away": 1,
                "wl": "L",
                "pts": 90,
                "reb": 38,
                "ast": 20,
                "stl": 6,
                "blk": 4,
                "fg3m": 10,
                "tov": 13,
                "plus_minus": -10,
            },
            {
                "game_id": 2,
                "game_date": "2099-10-05",
                "season": "2099-00",
                "season_type": "Regular Season",
                "team_id": 1,
                "team_abbr": "ALP",
                "team_name": "Alpha",
                "opponent_team_id": 2,
                "opponent_team_abbr": "BET",
                "opponent_team_name": "Beta",
                "is_home": 0,
                "is_away": 1,
                "wl": "L",
                "pts": 95,
                "reb": 39,
                "ast": 22,
                "stl": 7,
                "blk": 3,
                "fg3m": 11,
                "tov": 12,
                "plus_minus": -5,
            },
            {
                "game_id": 2,
                "game_date": "2099-10-05",
                "season": "2099-00",
                "season_type": "Regular Season",
                "team_id": 2,
                "team_abbr": "BET",
                "team_name": "Beta",
                "opponent_team_id": 1,
                "opponent_team_abbr": "ALP",
                "opponent_team_name": "Alpha",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "pts": 105,
                "reb": 41,
                "ast": 24,
                "stl": 9,
                "blk": 6,
                "fg3m": 14,
                "tov": 10,
                "plus_minus": 5,
            },
            {
                "game_id": 3,
                "game_date": "2099-10-10",
                "season": "2099-00",
                "season_type": "Regular Season",
                "team_id": 1,
                "team_abbr": "ALP",
                "team_name": "Alpha",
                "opponent_team_id": 3,
                "opponent_team_abbr": "GAM",
                "opponent_team_name": "Gamma",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "pts": 110,
                "reb": 42,
                "ast": 26,
                "stl": 8,
                "blk": 4,
                "fg3m": 15,
                "tov": 9,
                "plus_minus": 8,
            },
            {
                "game_id": 4,
                "game_date": "2099-10-11",
                "season": "2099-00",
                "season_type": "Regular Season",
                "team_id": 2,
                "team_abbr": "BET",
                "team_name": "Beta",
                "opponent_team_id": 4,
                "opponent_team_abbr": "DEL",
                "opponent_team_name": "Delta",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "pts": 120,
                "reb": 43,
                "ast": 27,
                "stl": 10,
                "blk": 5,
                "fg3m": 16,
                "tov": 8,
                "plus_minus": 12,
            },
        ]
    )

    a_df, b_df = _build_team_head_to_head_frames(
        df,
        team_a="ALP",
        team_b="BET",
        home_only=True,
    )

    assert len(a_df) == 1
    assert len(b_df) == 1
    assert a_df.iloc[0]["game_id"] == 1
    assert b_df.iloc[0]["game_id"] == 1
    assert a_df.iloc[0]["is_home"] == 1
    assert b_df.iloc[0]["is_away"] == 1


def test_player_head_to_head_frames_only_keep_shared_matchups_and_primary_home_filter():
    df = pd.DataFrame(
        [
            {
                "game_id": 1,
                "game_date": "2099-10-01",
                "season": "2099-00",
                "season_type": "Regular Season",
                "player_id": 100,
                "player_name": "Nikola Jokić",
                "team_id": 1,
                "team_abbr": "DEN",
                "team_name": "Denver Nuggets",
                "opponent_team_id": 2,
                "opponent_team_abbr": "PHI",
                "opponent_team_name": "Philadelphia 76ers",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "minutes": 36,
                "pts": 30,
                "reb": 12,
                "ast": 10,
                "stl": 1,
                "blk": 1,
                "fg3m": 2,
                "plus_minus": 8,
            },
            {
                "game_id": 1,
                "game_date": "2099-10-01",
                "season": "2099-00",
                "season_type": "Regular Season",
                "player_id": 200,
                "player_name": "Joel Embiid",
                "team_id": 2,
                "team_abbr": "PHI",
                "team_name": "Philadelphia 76ers",
                "opponent_team_id": 1,
                "opponent_team_abbr": "DEN",
                "opponent_team_name": "Denver Nuggets",
                "is_home": 0,
                "is_away": 1,
                "wl": "L",
                "minutes": 35,
                "pts": 25,
                "reb": 11,
                "ast": 4,
                "stl": 0,
                "blk": 2,
                "fg3m": 1,
                "plus_minus": -8,
            },
            {
                "game_id": 2,
                "game_date": "2099-10-05",
                "season": "2099-00",
                "season_type": "Regular Season",
                "player_id": 100,
                "player_name": "Nikola Jokić",
                "team_id": 1,
                "team_abbr": "DEN",
                "team_name": "Denver Nuggets",
                "opponent_team_id": 2,
                "opponent_team_abbr": "PHI",
                "opponent_team_name": "Philadelphia 76ers",
                "is_home": 0,
                "is_away": 1,
                "wl": "L",
                "minutes": 37,
                "pts": 27,
                "reb": 13,
                "ast": 9,
                "stl": 2,
                "blk": 0,
                "fg3m": 1,
                "plus_minus": -4,
            },
            {
                "game_id": 2,
                "game_date": "2099-10-05",
                "season": "2099-00",
                "season_type": "Regular Season",
                "player_id": 200,
                "player_name": "Joel Embiid",
                "team_id": 2,
                "team_abbr": "PHI",
                "team_name": "Philadelphia 76ers",
                "opponent_team_id": 1,
                "opponent_team_abbr": "DEN",
                "opponent_team_name": "Denver Nuggets",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "minutes": 36,
                "pts": 31,
                "reb": 10,
                "ast": 5,
                "stl": 1,
                "blk": 1,
                "fg3m": 0,
                "plus_minus": 4,
            },
            {
                "game_id": 3,
                "game_date": "2099-10-10",
                "season": "2099-00",
                "season_type": "Regular Season",
                "player_id": 100,
                "player_name": "Nikola Jokić",
                "team_id": 1,
                "team_abbr": "DEN",
                "team_name": "Denver Nuggets",
                "opponent_team_id": 3,
                "opponent_team_abbr": "LAL",
                "opponent_team_name": "Los Angeles Lakers",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "minutes": 34,
                "pts": 28,
                "reb": 12,
                "ast": 8,
                "stl": 1,
                "blk": 1,
                "fg3m": 2,
                "plus_minus": 9,
            },
            {
                "game_id": 4,
                "game_date": "2099-10-11",
                "season": "2099-00",
                "season_type": "Regular Season",
                "player_id": 200,
                "player_name": "Joel Embiid",
                "team_id": 2,
                "team_abbr": "PHI",
                "team_name": "Philadelphia 76ers",
                "opponent_team_id": 4,
                "opponent_team_abbr": "BOS",
                "opponent_team_name": "Boston Celtics",
                "is_home": 1,
                "is_away": 0,
                "wl": "W",
                "minutes": 35,
                "pts": 29,
                "reb": 9,
                "ast": 4,
                "stl": 1,
                "blk": 2,
                "fg3m": 1,
                "plus_minus": 7,
            },
        ]
    )

    a_df, b_df = _build_player_head_to_head_frames(
        df,
        player_a="Nikola Jokić",
        player_b="Joel Embiid",
        home_only=True,
    )

    assert len(a_df) == 1
    assert len(b_df) == 1
    assert a_df.iloc[0]["game_id"] == 1
    assert b_df.iloc[0]["game_id"] == 1
    assert a_df.iloc[0]["is_home"] == 1
    assert b_df.iloc[0]["is_away"] == 1
