"""Leaderboard stat alias tables and phrase-detection helpers."""

from __future__ import annotations

import re

LEADERBOARD_STAT_ALIASES: dict[str, str] = {
    "true shooting percentage": "ts_pct",
    "true shooting %": "ts_pct",
    "true shooting": "ts_pct",
    "effective field goal percentage": "efg_pct",
    "effective field goal %": "efg_pct",
    "effective field goal": "efg_pct",
    "effective fg %": "efg_pct",
    "effective fg": "efg_pct",
    "assists per game": "ast",
    "rebounds per game": "reb",
    "points per game": "pts",
    "steals per game": "stl",
    "blocks per game": "blk",
    "turnovers per game": "tov",
    "three pointers made": "fg3m",
    "three-point makes": "fg3m",
    "threes made": "fg3m",
    "30-point games": "games_30p",
    "30 point games": "games_30p",
    "40-point games": "games_40p",
    "40 point games": "games_40p",
    "20-point games": "games_20p",
    "20 point games": "games_20p",
    "10-assist games": "games_10a",
    "10 assist games": "games_10a",
    "10-rebound games": "games_10r",
    "10 rebound games": "games_10r",
    "scorers": "pts",
    "scoring": "pts",
    "points": "pts",
    "rebounding": "reb",
    "rebounders": "reb",
    "rebounds": "reb",
    "assists": "ast",
    "steals": "stl",
    "steal": "stl",
    "blocks": "blk",
    "block": "blk",
    "shot blockers": "blk",
    "shot-blockers": "blk",
    "turnovers": "tov",
    "turnover": "tov",
    "plus minus": "plus_minus",
    "plus/minus": "plus_minus",
    "plus_minus": "plus_minus",
    "+/-": "plus_minus",
    "apg": "ast",
    "rpg": "reb",
    "ppg": "pts",
    "spg": "stl",
    "bpg": "blk",
    "3pm": "fg3m",
    "threes": "fg3m",
    "ts pct": "ts_pct",
    "ts%": "ts_pct",
    "efg pct": "efg_pct",
    "efg%": "efg_pct",
    "usage rate": "usg_pct",
    "usage percentage": "usg_pct",
    "usage %": "usg_pct",
    "usage": "usg_pct",
    "usg%": "usg_pct",
    "usg pct": "usg_pct",
    "usg_pct": "usg_pct",
    "assist percentage": "ast_pct",
    "assist %": "ast_pct",
    "ast%": "ast_pct",
    "ast pct": "ast_pct",
    "ast_pct": "ast_pct",
    "rebound percentage": "reb_pct",
    "rebound %": "reb_pct",
    "reb%": "reb_pct",
    "reb pct": "reb_pct",
    "reb_pct": "reb_pct",
    "turnover percentage": "tov_pct",
    "turnover %": "tov_pct",
    "turnover rate": "tov_pct",
    "tov%": "tov_pct",
    "tov pct": "tov_pct",
    "tov_pct": "tov_pct",
    "offensive rating": "off_rating",
    "off rating": "off_rating",
    "off_rating": "off_rating",
    "defensive rating": "def_rating",
    "def rating": "def_rating",
    "def_rating": "def_rating",
    "net rating": "net_rating",
    "net_rating": "net_rating",
}

TEAM_LEADERBOARD_STAT_ALIASES: dict[str, str] = {
    "best offensive teams": "off_rating",
    "offensive teams": "off_rating",
    "best offense": "off_rating",
    "offensive rating": "off_rating",
    "off rating": "off_rating",
    "off_rating": "off_rating",
    "worst offensive teams": "off_rating",
    "best defensive teams": "def_rating",
    "defensive teams": "def_rating",
    "best defense": "def_rating",
    "defensive rating": "def_rating",
    "def rating": "def_rating",
    "def_rating": "def_rating",
    "worst defensive teams": "def_rating",
    "teams with most threes": "fg3m",
    "most threes per game teams": "fg3m",
    "most threes per game": "fg3m",
    "teams with best efg%": "efg_pct",
    "teams with best efg pct": "efg_pct",
    "best team efg%": "efg_pct",
    "best efg% teams": "efg_pct",
    "teams with best ts%": "ts_pct",
    "teams with best ts pct": "ts_pct",
    "best team ts%": "ts_pct",
    "best ts% teams": "ts_pct",
    "best net rating teams": "net_rating",
    "best net rating": "net_rating",
    "net rating": "net_rating",
    "net_rating": "net_rating",
    "worst net rating teams": "net_rating",
    "fastest teams": "pace",
    "fastest pace teams": "pace",
    "highest pace teams": "pace",
    "slowest teams": "pace",
    "slowest pace teams": "pace",
    "lowest pace teams": "pace",
    "pace": "pace",
    "most steals teams": "stl",
    "team steals": "stl",
    "most blocks teams": "blk",
    "team blocks": "blk",
    "most turnovers teams": "tov",
    "team turnovers": "tov",
    "lowest turnover teams": "tov",
    "fewest turnovers teams": "tov",
    "fewest turnover teams": "tov",
    "best plus minus teams": "plus_minus",
    "best plus/minus teams": "plus_minus",
    "team plus minus": "plus_minus",
    "most wins": "wins",
    "most wins teams": "wins",
    "teams with most wins": "wins",
    "best record teams": "win_pct",
    "best record": "win_pct",
    "best winning percentage": "win_pct",
    "best win pct": "win_pct",
    "highest winning percentage": "win_pct",
    "most losses": "losses",
    "most losses teams": "losses",
    "teams with most losses": "losses",
    "fewest losses": "losses",
    "fewest losses teams": "losses",
    "best scoring teams": "pts",
    "highest scoring teams": "pts",
    "most points per game teams": "pts",
    "most rebounds teams": "reb",
    "most assists teams": "ast",
}


def _matches_loose_phrase(text: str, phrase: str) -> bool:
    return bool(re.search(rf"(?<!\w){re.escape(phrase)}(?!\w)", text))


def _detect_leaderboard_stat(text: str, aliases: dict[str, str]) -> str | None:
    for key in sorted(aliases.keys(), key=len, reverse=True):
        if _matches_loose_phrase(text, key):
            return aliases[key]
    return None


def detect_player_leaderboard_stat(text: str) -> str | None:
    return _detect_leaderboard_stat(text, LEADERBOARD_STAT_ALIASES)


def detect_team_leaderboard_stat(text: str) -> str | None:
    return _detect_leaderboard_stat(text, TEAM_LEADERBOARD_STAT_ALIASES)


def wants_ascending_leaderboard(text: str) -> bool:
    """Detect if the leaderboard should sort ascending (lowest/fewest/least/bottom)."""
    return bool(re.search(r"\blowest\b|\bfewest\b|\bleast\b|\bworst\b|\bbottom\b", text))
